import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Background from "../components/background";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Background />
      <main className={styles.main}>
        <div className={styles.titleContainer}>
          <h2 className={`${styles.title} ${styles.fadedTitle}`}>superdigitAl</h2>
          <h1
            className={`${styles.title} ${styles.glitch} ${styles.layers}`}
            data-text="superdigitAl"
          >
            <span>superdigitAl</span>
          </h1>
          <h2 className={`${styles.title} ${styles.fadedTitle}`}>superdigitAl</h2>
        </div>
        <section className={styles.content}>
          <p> Test </p>
        </section>
      </main>
    </div>
  );
};

export default Home;
