import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Background from "../components/background";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Background />
      <main className={styles.main}>
        <h1
          className={styles.title + " " + styles.glitched + " " + styles.layers}
          data-text="superdigitAl"
        >
          superdigitAl
        </h1>
      </main>
    </div>
  );
};

export default Home;
